fragment PageParts on Page {
  __typename
  title
  heading
  subheading
  backgroundImage
  contentTitle
  content
  body
  paragraph1
  paragraph2
  resources {
    __typename
    title
    links {
      __typename
      text
      url
    }
    images {
      __typename
      src
      alt
      link
    }
    showDivider
  }
}
